# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Image
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and publish
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mount BTRFS for docker storage
        env:
          BTRFS_TARGET_DIR: "/var/lib/docker"
          BTRFS_MOUNT_OPTS: "compress-force=zstd:1"
        run: ${{ github.workspace }}/.github/workflows/mount_btrfs.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: github.com/Zeglius/bootc-dagger/ci@main
          verb: call
          args: new-builder ${{ github.event_name == 'pull_request' && ' --dry-run' || '' }} --cfg-file=./bootc-ci.yaml --build-context=. --secrets=env://GITHUB_SHA,env://GITHUB_REPOSITORY,env://CI,env://GITHUB_REPOSITORY_OWNER,env://GITHUB_REF_NAME build
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
